apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "jammy-server-amd64"
  labels:
    app: containerized-data-importer
  annotations:
    cdi.kubevirt.io/storage.import.endpoint: "https://cloud-images.ubuntu.com/jammy/20220810/jammy-server-cloudimg-amd64-disk-kvm.img"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
